### ISSUE TITLE
Migration and seed script

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-api#10]
Need scripts that run the migrations and seeds properly.

Requirements:
1. Want to store changes as SQL files (for flexibility and also for syntax highlighting)
2. Don't want to write code unnecessarily

Options:
1. Use `knex` migration API, store migrations as SQL files, have JS files with same names as SQL files as interface to `knex`.
  * Pros: Only need to write SQL code
  * Cons: Twice as many files (albeit JS files will be ~3 lines)
2. Write own custom migration script that reads the SQL files.
  * Pros: No duplicated files
  * Cons: Need to write and test own code

I'd go for option 1. @astroash thoughts?

**Comment by astroash** [comment]
I have no preference.
