### ISSUE TITLE
getOne swallowing errors when called from other methods

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#101]
https://github.com/TwinePlatform/twine-api/blob/238795e83533244dc6ee9f24434ce177299fbd95/src/models/organisation.ts#L84-L87

`getOne` is called from many methods to return the first value, and if no matching value is found it returns `null`. This is a problematic when something goes wrong whilst inserting values in the original method as there is no indicator of the problem. It would be more appropriate for `getOne` to throw an error when no value is returned.

**Comment by eliascodes** [comment]
First, let's add a test that exercises this case.

Secondly, I reckon it should be the `add` methods that check whether the `insert` was done correctly, rather than this method, no?

**Comment by astroash** [comment]
> First, let's add a test that exercises this case.

I found this problematic when I was chaining methods from different models together, so not necessarily testable in this sense. These models are going to be going under a lot of revision over the next few weeks, and I think it would be useful to have as much feedback as possible about what is happening. 

> Secondly, I reckon it should be the add methods that check whether the insert was done correctly, rather than this method, no?

My issue is with the returning value. If a check is done in the calling method, and throws an error then this also resolves the issue.

**Comment by astroash** [comment]
This issue is superseded by #176. [Latest comment](https://github.com/TwinePlatform/twine-api/issues/176#issuecomment-426590388) offers a suggestion on how to avoid the above issues.
