### ISSUE TITLE
model questions

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#105]
Whilst setting up the login route, I have a number of questions about the current state of the models:
- what's the benefit of having `CbAdmins` and `Users` separate? If the intention is to have separate models for each user type, what benefit will this give us when setup?
- as we now have a constraint for one organisation per user, can organisation_id be added to the user model?
- Why is there `.toColumnNames` and `.ModelToColumn`? It seems that the former is filtering out values that are not passed in, but do they have majorly different use cases? If so I think the names need clarifying.
- is `.create` to typesafe values passed in from requests?

**Comment by eliascodes** [comment]
> what's the benefit of having CbAdmins and Users separate? If the intention is to have separate models for each user type, what benefit will this give us when setup?

`Users` contains the most generic code, applicable to all user types. Other user-related models can refer to or use the methods defined on this model. They can also define more elaborate/specific logic that is relevant only to that user type.

It may be that we find that there ends up being no direct use-case for the `Users` model, and it is just a way to reduce code-duplication, in which case we can think about whether it's still the best way to achieve that.

> as we now have a constraint for one organisation per user, can organisation_id be added to the user model?

This would probably be convenient, but my concern is precisely that; we would become over-reliant on accessing the `organisationId` from the user model that when/if the time comes to remove that constraint, we'll have lots of code to update. Actually, given that the organisation model/id is already stored in the `request.auth.credentials` in each handler, is this really that necessary?

> Why is there .toColumnNames and .ModelToColumn? It seems that the former is filtering out values that are not passed in, but do they have majorly different use cases? If so I think the names need clarifying.

I think the former can be defined in terms of the latter. We need to filter out values in the former to avoid problems with SQL generation. The latter is used as a static map for `select` statements, the former as a dynamic map to extract values from objects for use in `insert`/`update` statements.

> is .create to typesafe values passed in from requests?

Partly, yes. But also there may be additional operations that need to be performed when "creating" a brand new instance of a user (e.g. see the `Visitors.create` method).

**Comment by astroash** [comment]
**re `Users` model:**
- Currently we are mixing between getting methods from both `Users` and `CbAdmin`, which I think will be confusing in the long run. I want to avoid having multiple places we can call the same functionality. How do you feel about sticking to one of the following
  - duplicated methods aren't defined on sub-collections and are grabbed from the original eg. `CbAdmin.add` calls `Users.add` so is removed
  - `Users` is not called directly and only ever called from sub-collections.

https://github.com/TwinePlatform/twine-api/blob/efa9c3d2d8d1188cd3dbdf7660e2e208086b62d7/src/models/cb_admin.ts#L33-L57
- I'm keen to take advantage of being able to link queries together with transactions to avoid duplication. in `CbAdmin.get` there is very similar functionality to `Users.get`. Can we use a transaction to join methods on `Users` and `Roles` to achieve the same result.

**re `organisation_id` in `User` model**
- I think your correct in being careful on relying on this info too much. I needed to access it as part of the homepage login route and was thinking of the best way to access this information. I'm in favour of making our models more generic, rather than having to add lots of specific methods on collections, but in this case, I think that the extra method is warranted. 

**re `.toColumnNames` and `.ModelToColumn`**
- so am I correct in saying that `.toColumnNames` is the same as `.ModelToColumn` but also filters out undefined properties?

**re `.create`**
👌

**Comment by eliascodes** [comment]
> duplicated methods aren't defined on sub-collections and are grabbed from the original eg. CbAdmin.add calls Users.add so is removed

Don't like this.

> Users is not called directly and only ever called from sub-collections.

Can live with this in theory. We'll have to change the credentials object again back to IDs, and instead fetch the actual objects using route pre-requisites, which I think is actually fine tbh (pre-reqs can be run in parallel too, so that's good).

> I'm keen to take advantage of being able to link queries together with transactions to avoid duplication. in CbAdmin.get there is very similar functionality to Users.get. Can we use a transaction to join methods on Users and Roles to achieve the same result.

What are you suggesting?

> so am I correct in saying that .toColumnNames is the same as .ModelToColumn but also filters out undefined properties?

I don't know. `ModelToColumn` is just a static object. It doesn't _do_ anything. So in that sense they are nothing alike. But they are alike in the sense that they are describing a very similar, but not identical, mapping.

**Comment by eliascodes** [comment]
@astroash is there anything else to clear up?

**Comment by astroash** [comment]
Not for the moment. A lot of these issues were cleared up by the distinction between application and domain logic.
