### ISSUE TITLE
Cookies vs Local Storage

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#106]
New api will be serving all of our apps, so we will need to pick what type of stateless authentication we want to use. 

This is probably a no brainer as local storage does not support subdomains.

# 🍪 🎉 

Reference - [an article on the internet](https://www.moesif.com/blog/technical/restful-apis/Authorization-on-RESTful-APIs/)

**Comment by eliascodes** [comment]
Sure, lets go with cookies.
