### ISSUE TITLE
🐛 formatResponse is stripping headers

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#111]
https://github.com/TwinePlatform/twine-api/blob/b3a0da0647adc3608f0ff043b2bf630174f21fa7/src/api/v1/utils.ts#L31-L41

`formatResponse` function called from `api/v1/hooks/onPostHandler.ts` is stripping out response headers

**Comment by eliascodes** [comment]
I think we have to alter the value of the `source` key on the `res` object, then simply return the original `res` object. This should preserve all the response metadata.

**Comment by astroash** [comment]
On further investigation, you can configure routes with cors options so that [hapi sets cors headers](https://hapijs.com/api#-routeoptionscors) post lifecycle methods, so we don't have to worry about overwriting manually defined ones.

**Comment by eliascodes** [comment]
Yes, but if we do add any custom headers to the responses, this will still strip them. Low priority I guess, but still an issue IMO.

**Comment by eliascodes** [comment]
Add comment to code instead of keeping this issue open.
