### ISSUE TITLE
🍪 Setup cookies for stateless authentication

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#112]
- [ ] login route creates and sends auth cookie
- [ ] logout route removes cookie
- [ ] scheme checks cookie to verify login details

As the server and client are hosted on different domains CORS will need to be setup on the server:
- [hapi js route options for cors](https://github.com/hapijs/hapi/blob/master/API.md#-routeoptionscors)
- withCredentials needs to be set on axios to allow browser to set cookie

**Comment by astroash** [comment]
@eliascodes still struggling to get the browser to set a cookie. It would be great if you could have a look when you get a chance.
Weird things I've noticed:
- I dont think a preflight options request is being sent
- hapi route.options.cors is setting some headers but not all

**Comment by eliascodes** [comment]
@astroash did you read #110 before starting this?
