### ISSUE TITLE
VISITOR role permissions on routes

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#123]
The scope for a number of routes are intended for the `VISITOR` role, such as `POST /community-businesses/:id/visit_logs`, which allows visitors to add their visit. Visitors are only ever logged in when an `ORG_ADMIN` has logged in first, which brings up the following questions:
- Do we need scopes for visitors? Can these routes just be authenticated for `ORG_ADMIN`?
- will we be setting cookies for `VISITOR`s? Currently to add a visit log the users details are sent in a `POST` request along with the activity details.

With `VISITOR` cookie auth flow:
1. `ORG_ADMIN` logs in and admin auth cookie set
2. `VISITOR` scans QR code and visitor cookie is set
3. `VISITOR` clicks on activity they are attending. POST request with activity details is sent. Server reads visitor cookie for details then removes cookie in response. `ADMIN` cookie is still doing it's thing.

Without `VISITOR` cookie auth flow:
1. `ORG_ADMIN` logs in and admin auth cookie set
2. `VISITOR` scans QR code and visitor details are stored in react state
3. `VISITOR` clicks on activity they are attending. POST request with activity and visitor details is sent. React state is cleared on response.

**Comment by astroash** [comment]
relates #110

**Comment by eliascodes** [comment]
> will we be setting cookies for VISITORs?

I'm struggling to think of a good way to accommodate two authenticated users on the same user-agent. And given our use cases at the moment I'm not sure we really need to.

> Without VISITOR cookie auth flow:

I think I prefer this for now, and we should probably send the visitor's hash in the request that creates a visit event.

> Do we need scopes for visitors? Can these routes just be authenticated for ORG_ADMIN?

At the moment, I think no and yes, respectively.
