### ISSUE TITLE
Missing permissions for roles

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-api#126]
I think the `ORG_ADMIN` role has some erroneous permissions:

https://github.com/TwinePlatform/twine-api/blob/770c9e19e362e3303e6a45b8968b485fdab8d1c2/src/api/v1/permissions.json#L73-L93

All `organisations_details-child:xxx` should be `organisations_details-own:xxx`, same with `organisations_training-child:xxx`, `organisations_feedback-child:xxx` and `organisations_outreach-child:read`.

`visit_logs-child:read` should probably be `visit_logs-own:read` since `VISITOR` only has `visit_logs-parent:write`.

**Comment by astroash** [comment]
@eliascodes check the api.json file to see which routes these permissions are coming from, and whether you think they are correct.
