### ISSUE TITLE
Tech choices for frontend dashboards 

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#14]
Currently the php app is using server rendered templates for the current dashboard. Moving forward we need to rewrite this is another framework/language to be supported by the node server. 

Choices:

λ    elm
👴🏼 handlebars
🔺 angular (server/client rendered)
⚛️ react (server/client rendered)

Deciding on tech stack will effect which, if any, static type library is chosen #8. Relates to #9 
___
I _reluctantly_ feel like react, either client or server rendered, would be the best choice moving forward.  It will minimise content switching as one app is already written in js/react, and moves us one step closer to cohesive tech stack. It is also currently an extremely popular framework which ensures it will easy to support maintain in the future.

**Comment by eliascodes** [comment]
This isn't related to the API, should be in hq.
