### ISSUE TITLE
Generate files for changes to permissions in db

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#140]
Permissions are currently added to the db from a `permissions.json`. This file is mostly generated from the `api.json` but has some manual edits see: https://github.com/TwinePlatform/twine-api/pull/124/files

As permissions change in future it would be great to be able to generate knex migration files from our api spec.

prereqs
- [ ] update `api.json`'s `intendedFor`, so that it is an object rather than an array to match roles and scopes

This has partially been started on #139.

**Comment by eliascodes** [comment]
No longer relevant given #339
