### ISSUE TITLE
Missing postmark typings

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-api#150]
`Attachments` is missing from the typings provided by `@types/postmark`. We should (at least) make an issue on DefinitelyTyped, and possibly contribute a fix.

Use this issue to record any other problems with the postmark typings.

The ultimate aim should be to remove our modified version of the postmark typings from source control.

**Comment by astroash** [comment]
https://github.com/TwinePlatform/twine-api/blob/d34a3384c1a6c8e3da3a86cdcf54025941e630ff/src/services/email/postmark.d.ts#L7

☝️ I think this means that:
- the ts Client class did not allow options argument to be optional so an empty object had to be passed to appease the compiler.

**Comment by eliascodes** [comment]
Closed by #225
