### ISSUE TITLE
🐛 Pdf Service errors when used with register route

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#159]
<img width="1074" alt="screen shot 2018-09-18 at 11 35 35 pm" src="https://user-images.githubusercontent.com/14337958/45720288-ace7d680-bb9b-11e8-9a1c-2de482a04a97.png">

Error seems to be caused on line 30 of the following file:

https://github.com/TwinePlatform/twine-api/blob/238795e83533244dc6ee9f24434ce177299fbd95/src/services/pdf/index.ts#L25-L36

**Comment by eliascodes** [comment]
This opened up a can of worms 🙄. PRs incoming.
