### ISSUE TITLE
Authentication routes

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-api#170]
Visitor app (cookie):
* Should only support cb admins logging in

Volunteer app (header):
* Should support volunteers and volunteer admins logging in
* Possibly should also support cb admins logging in

Dashboard (cookie):
* Should only support cb admins logging in

URLs in a RESTful API should describe resources or actions, and ideally we would aim not to over-specialise endpoints to serve only a single client application (we have done this in the past, but largely out of pragmatism; we didn't know enough about use cases to generalise).

Suggestion: use query or payload parameters to constrain behaviour of route:
`/users/login?restrict={role}&type={cookie | header}`

This is ultimately not that different from having `/users/login/admin`, `/users/login/volunteer`, etc, but doesn't require several routes to describe one semantic, and is more explicit in what it means at face value. Multiple allowed roles are supported through arrays in `?restrict[]={role1}&restrict[]={role2}`.

Not that fussed whether these should be query params or payload params.

**Comment by astroash** [comment]
@eliascodes would you be able to add something to the documentation regarding this choice so we can close this issue?

**Comment by astroash** [comment]
@eliascodes bump

**Comment by eliascodes** [comment]
I think this should be de-prioritised until there is more clarity on #110

**Comment by astroash** [comment]
@eliascodes can this be closed?
