### ISSUE TITLE
Error handling in models

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-api#176]
There's some inconsistency in how errors are being handled in the models. We should determine how to treat programmer errors and how to treat other errors that can be anticipated, and also what exactly constitutes a programmer error.

May be worth looking in https://github.com/hapijs/bounce

**Comment by astroash** [comment]
My current thoughts on this are...

In models:
- any method that is retrieving data should return null if resource is not found
- any method that is updating/deleting a resource should throw an error if the incorrect resource type is given

eg. 
- I am looking for a specific cb `Cb.getOne` will return null if incorrect name is passed
- I am updating a specific cb `Cb.update` will throw an error if a funding body is passed

In handlers there are two ways we can work with the above errors
- always use `Collection.exists` before passing resources to update/delete methods
- pass any old thing but always wrap in a try/catch to return appropriate error

**Comment by eliascodes** [comment]
I ended up thinking about this from a wider perspective than just the models.

I think this is mostly about async functions. So it's ultimately a discussion about whether rejected promises should be used to characterise both system/programmmer errors and application errors, or not.

Initially I wanted to save rejected promises for handling system errors only. Now that I've read a bit more about `bounce`, I think it's a decent solution to the problem and allows us to represent both error types with a rejected promise.

> any method that is retrieving data should return null if resource is not found

Agree if the method is claiming to retrieve _a single_ record, but if it is claiming to retrieve a collection of records, it should just return an empty container (usually array, possibly object).

> any method that is updating/deleting a resource should throw an error if the incorrect resource type is given

I don't remember the extent to which we've discussed this already, but IMO I think it's fine to throw in the model methods to catch programmer errors that aren't caught by the compiler (e.g. passing the wrong type of user), but I don't think we want to throw if, for example, an update affects 0 rows. That is not necessarily a failure case, and it should be left up to the calling code to interpret and act accordingly.

> pass any old thing but always wrap in a try/catch to return appropriate error

I prefer this.

I think in addition, it could be worth each application area throwing sub-classed instances of `Error` so that we can easily tell which components of the system are throwing. This doesn't need to be that fine-grained, just something like `ModelError`, `APIError`, `EmailServiceError`, etc.

Trying to summarise:
1. Methods that retrieve a single resource
   * return `null` if the inputs are valid but return no results
   * throw if inputs result in failing query (programmer error)
2. Methods that retrieve a collection of resources
   * return empty collection (`[]` or `{}`) if inputs are valid but return no results
   * throw if inputs result in failing query (programmer error)
3. Methods that create resources
   * throw if inputs result in failing query (programmer error)
4. Methods that mutate a single resource
   * should not treat the degenerate case (of a no-change update) differently
   * should throw if query targets multiple resources (programmer error)
   * throw if inputs result in failing query (programmer error)
5. Methods that mutate several resources
   * should not treat the degenerate case (of a no-change update) differently
   * throw if inputs result in failing query (programmer error)
6. `bounce` should be used to catch application errors but re-throw programmer errors
7. System errors ([see here](https://github.com/hapijs/bounce/blob/2b21702a6954c857f00c5a9c88963c8d5197f7f4/lib/index.js#L14-L28)) should not be replaced by application errors unless there's a _very_ good reason
8. Handlers should only wrap calls in `try/catch` if:
   * they anticipate an application error could be thrown
   * they need to perform some clean-up before propagating a system error up the stack

How does that sound?

**Comment by eliascodes** [comment]
>  Are you describing a knex/pg error here? Or describing some type of checks in models?

As far as the models go, yes this would be a `knex` error, but more widely, this would be an error thrown by the code called in the body of the function (not an explicit `throw` in the body).

> Can you think of any other cases for this other than the wrong user type mentioned above?

Invalid foreign key references

> What do you consider a degenerate case?

Either update columns (x, y, ...) to values identical to their current value, or update no rows at all. Not sure what is meant by `"wrong type"` in `"attempt to update a non existing id (because it's the wrong type)"`. 

> attempt to update a non existing id (because it doesnt exists)

I think this would be a programmer error, because it would require a change to the code to fix. So this should throw.

> What's your definition of application error and programmer error?

A programmer error is a bug. The only way it can be resolved is with a change to the code. It is by definition unanticipated, and can leave the application in an unknown state. Applications should not attempt to recover from these.

An application error is caused by external factors (disk/network failures, bad user input). They are routine and should be anticipated and handled explicitly.

> Do you have a hypothetical example of this?

Resetting any changes to the database to prevent it being left in an inconsistent state. It may be that there are two critical operations in a handler, one of which is not related to the DB (or is related to a different DB), so they cannot be put into a transaction.
