### ISSUE TITLE
Volunteer admin codes

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-api#184]
Related to TwinePlatform/twine-app#22, TwinePlatform/data-sync#18

These admin codes have been mistakenly modeled as one-time codes. In fact they are long-lived tokens.

This requires the following changes to the DB model:
* `single_use_token` renamed to `token`
* `single_use_token.expires_at` made nullable
* `volunteer_admin_one_time_code` renamed to `volunteer_admin_code`
* `user_id` foreign key replaced with `organisation_id` foreign key

These tokens should also probably be hashed before storage.

**Comment by astroash** [comment]
@eliascodes on second thought I now thing that `volunteer_admin_code` should be a table independent to `single_use_token`. We already having a separate `api_token` table, which would get confusing if added a generic `token` table.

`single_use_token` table has a clear use case, and as the app grows a number of other tables can be linked for inviting cbs/funding bodies/volunteers.

Changes needed:
- rename `volunteer_admin_one_time_code` to `volunteer_admin_one_time_code`
- repurpose above table to link directly to `organisation` and add code column

**Comment by astroash** [comment]
@eliascodes do we still want these tokens to be hashed?

I'm indifferent on the matter.

**Comment by eliascodes** [comment]
I guess given we need to display them on the twine dashboard, we can't really hash them.
