### ISSUE TITLE
🗃 Resources n their relations

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#187]
### Current Resources and their ownership
**organisations - 🏢 owned by ORG**
organisations_details
organisations_subscriptions
organisations_feedback
organisations_training
organisations_invitations
organisations_outreach

**volunteers - 🏢 owned by ORG**
volunteer_activities
volunteer_logs

**visitors - 🏢 owned by ORG**
visit_activities
visit_logs

**users - 🙍🏾‍♂️ owned by USER**
user_details

### Proposed Resources and their ownership
**organisations - 🏢 owned by ORG**
organisations_details
organisations_subscriptions
organisations_feedback
organisations_training
organisations_invitations
organisations_outreach
visit_activities
volunteer_activities

**users - 🙍🏾‍♂️ owned by USER**
user_details
volunteer_logs
visit_logs

### Changes
I think that `volunteer_logs` should be owned by volunteers, whereas `volunteer_activities` should be owned by the org. This should be the same for visitors.
- Volunteers/Visitors are the ones actively making the transaction by attending an activity/volunteering and signing in. 
- We are holding the functionality for users to be able to signed up to numerous orgs. When this is implemented users will be able to view their logs across orgs, this should be them accessing their data, rather than requesting permission to access multiple orgs data.
- This is mirrored in our endpoint layout
`GET /users/volunteers/me/volunteer-logs` allows users to access their own logs

### Permission Changes

TWINE_ADMIN

"visit_activities-child:read",
"visit_logs-child:read",
"volunteer_logs-child:read"

FUNDING_BODY

"visit_activities-child:read",
"visit_logs-child:read",
"volunteer_logs-child:read"

ORG_ADMIN
"visit_activities-own:delete",
"visit_activities-own:read",
"visit_activities-own:write",
"visit_logs-own:read" -> "visit_logs-child:read",
"visit_logs-own:write" -> "visit_logs-child:write",
"volunteer_logs-own:read" -> "volunteer_logs-child:read"

VOLUNTEER

"volunteer_logs-parent:delete" -> "volunteer_logs-own:delete",
"volunteer_logs-parent:read" -> "volunteer_logs-own:read",
"volunteer_logs-parent:write" -> "volunteer_logs-own:write"

VOLUNTEER_ADMIN

"volunteer_logs-parent:delete" -> "volunteer_logs-own:delete",
"volunteer_logs-parent:read" -> "volunteer_logs-own:read",
"volunteer_logs-parent:write" -> "volunteer_logs-own:write"
”volunteer_logs-sibling:read” **new**
”volunteer_logs-sibling:write” **new**
”volunteer_logs-sibling:delete” **new**

**Comment by astroash** [comment]
Oops, forgot to add the new sibling scope. Amended the previous comment.

With volunteers owning their own logs, volunteer admin can add/edit/delete others logs with the sibling flags.

**Comment by eliascodes** [comment]
So just to summarise...

`isSiblingUser` is `true` if:
* both target and user are `VOLUNTEER` | `VISITOR` | `VOLUNTEER_ADMIN` at CB `X`
* both target and user are `ORG_ADMIN` at CB `X` (not supported at the moment)

`isChildUser` is `true` if:
* user is `ORG_ADMIN` at CB `X` and target is `VOLUNTEER` | `VISITOR` | `VOLUNTEER_ADMIN` at CB `X`
* user is `ORG_ADMIN` at funding body `X`, which funds CB `Y`, and target is `ORG_ADMIN` | `VOLUNTEER` | `VISITOR` | `VOLUNTEER_ADMIN` at CB `Y`
* user is `TWINE_ADMIN`

`isParentUser` is no longer necessary as there are no `parent` scopes.

Is this correct?

**Comment by astroash** [comment]
> both target and user are ORG_ADMIN at CB X (not supported at the moment)

`ORG_ADMIN` are not considered a sibling, as they are a BIG BOSS (higher level) user. They are effectively the `ORG`. They access `VOLUNTEER` |` VISITOR` | `VOLUNTEER_ADMIN` owned data by using the `-parent` flag

**Comment by eliascodes** [comment]
> by using the `-parent` flag

You meant the `-child` flag, no?

**Comment by astroash** [comment]
Lol, yes I do.

**Comment by astroash** [comment]
@eliascodes how do you want to move forward? Do you want to implement this in #179 or in a separate PR?

**Comment by eliascodes** [comment]
I'd prefer to cover it separately, tbh, mainly cos that's the tip of a 3-PR chain 😕

**Comment by eliascodes** [comment]
Fixed by #200
