### ISSUE TITLE
🤔 Adding timestamp columns to database constants

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#191]
Currently we are grabbing a number of constants from the database such as regions, sectors and genders. These tables do not have timestamp columns which means that all constant routes in the api will return every db row.

If in the future any of these constants change we will need to hard delete rows, which will not allow us to support 'legacy' data which may be linked to old constants. 

I suggest we add the standard `created_at`, `modified_at`, `deleted_at` columns for all of these tables for flexibility of future use cases

**Comment by astroash** [comment]
By legacy, I don't mean legacy apps. I was describing data that was created and linked to constants which are later removed. We are no longer supporting those constants, but the data linked to it still holds value, and should still be searchable/filterable/aggregatable(?) by the original constant foreign key. For example
- visitors log their visits with the current user data available
- in 2020 the world finally gets bored of binary genders and unanimously decides to allow people to assign their gender to the farm animal they identify with most
- any data pre 2020 needs to submitted aggregated by regressive gender identities
- all the queries break because, _rightfully so_, binary gender names have been HARD DELETED from the database

Your concept of supporting legacy apps with our db model is also intriguing, but I won't answer that right now, as I should probably do some work.

**Comment by eliascodes** [comment]
OK lets do it.

**Comment by astroash** [comment]
bring the fight against binary genders?
