### ISSUE TITLE
♻️ redesign api.json

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#195]
`api.json` was a good document for planning out the structure of the api, but has now become tedious to update, with little benefit. The document in its current form should be archived, and replaced with map of routes and their intended users/scopes:

```
{
   [route_name]:  {
      [user]: [scope]
  }
}
```

**Comment by astroash** [comment]
@eliascodes do we want to continue having a key for `isImplemented`?

**Comment by eliascodes** [comment]
I don't think so. In the `api.json` we used it as a filter for the generated tests, but I guess we wont need that now.

**Comment by eliascodes** [comment]
Fixed by #200
