### ISSUE TITLE
Spiking authentication & authorisation

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-api#2]
Research and adopt best practices, particularly for resource access control.

**Comment by eliascodes** [comment]
Questions we may want to answer RE: permissions:
* What roles and permissions does this user have?
* What users have this role/permission?
* Does user X have role/permission Y?
* Assign user X to role Y
* Assign role X to permission Y
* Remove user X from role Y
* Revoke permission X from role Y
* Remove user X from all roles
* Revoke all permissions from role Y

The API for permissions should be separate from the API for roles.

Having more methods/functions, explicitly named, with tighter signatures, is IMO better than having large config objects for fewer functions.

```js
const Permissions = require('./permissions');
const Roles = require('./roles');
const User = require('../user');

// Permissions.grant :: Permission -> Resource -> Role -> Promise ()
// Permissions.revoke :: Permission -> Resource -> Role -> Promise ()
// Permissions.grantAll :: Resource -> Role -> Promise ()
// Permissions.revokeAll :: Resource -> Role -> Promise ()
// Permissions.roleHas :: Permission -> Role -> Promise Boolean
// Permissions.userHas :: Permission -> User -> Promise Boolean

// Roles.add :: Role -> User -> Promise ()
// Roles.remove :: Role -> User -> Promise ()
// Roles.move :: Role -> Role -> User -> Promise ()
// Roles.removeUserFromAll :: User -> Promise ()
// Roles.hasPermission :: Permission -> Promise Boolean
// Roles.userHas :: User -> Promise Boolean

// Examples:
Permissions.grant(Permissions.WRITE, 'visitor', Roles.ORG_ADMIN);
Permissions.revoke(Permissions.DELETE, 'volunteer_hours', Roles.VOLUNTEER);

User.byId(1).then(user => Roles.add(Roles.VOLUNTEER, user));
User.byEmail('foo@bar.com').then(user => Roles.remove(Roles.VISITOR, user));
```

If it's really necessary, we can think of variants of the above that perform batch actions something like:
```js
// Permissions.grantMany :: [Permissions] -> [Resource] -> [Role] -> Promise ()
// Permissions.revokeMany :: [Permissions] -> [Resource] -> [Role] -> Promise ()
```

Still don't have a firm handle on how we should treat `Resource`s, whether they should be enumerated constants, or just strings 🤷‍♂️.

**Comment by astroash** [comment]
@eliascodes what's your definition of a resource?

**Comment by eliascodes** [comment]
> what's your definition of a resource?

That's the question I'm struggling to answer. It may be that a resource maps directly onto a database table, but that leaks our specific implementation of the DB into the code in a way that is probably not necessary. It might be higher level entity, for example, the concept of an "organisation" includes things that aren't included directly in the `organisation` table (like `organisation_region` and `organisation_sector`, and "parent" or "child" organisations).

------------------------

Side note: we mentioned we'd want to have a way to describe a permission level where you can access only the resources you own. That might look like:

```js
Permissions.grant(Permissions.WRITE_OWN, 'user', Roles.VISITOR);
```

I think that's more natural than specifying it on the resource like this:

```js
Permissions.grant(Permissions.WRITE, 'user_own', Roles.VISITOR);
```

Implications of this, though are that the `permission` table needs to be different. Options are, IMO:
1. 6 columns, READ/WRITE/DELETE x OWN/ALL
2. 0/1/2 values for READ/WRITE/DELETE
3. OWN/ALL enum values for READ/WRITE/DELETE

I think I like the last option best.

**Comment by astroash** [comment]
A quick read around online on RBAC permission systems, suggests that key data to be capturing in db is:
> **Role**: a job function or title, which defines a person’s authority level
> **Permission**: the ability to view or modify a class of functionality
> **Operation**: a specific action in your system, which may require multiple permissions to be usable

And that access should be granted on said permissions. This implies granular control, which will make endpoint scopes rather large. One way to easily manage this could be to group permissions into categories which are used as endpoint scopes. 

[Designing an enterprise RBAC system](https://hackernoon.com/designing-an-enterprise-role-based-access-control-rbac-system-96e645c659b7)  
[How To Structure Permissions In A SaaS App](https://heapanalytics.com/blog/engineering/structure-permissions-saas-app)

**Comment by astroash** [comment]
# roles <> permissions <> operations

## permission flags
*-all - all data related to resource
*-children - data of all child catagories
*-parent - data of all parent catagories
*-own - data directly owned by user

## resources
### organisations
organisations_details
organisations_subscriptions
organisations_feedback
organisations_training
organisations_invitations
organisations_outreach

### users
users_details

### volunteers
volunteer_activities
volunteer_logs

### visit_activities
visit_activites
visit_logs

## roles ❤️ permissions

### visitor
organisations_details-parent:read

user_details-own:read
user_details-own:write
user_details-own:modify

visit_activties-parent:read

visit_logs-parent:write

### volunteer
organisations_details-parent:read
organisations_feedback-parent:write

user_details-own:read
user_details-own:write
user_details-own:modify

volunteer_activties-parent:read

volunteer_logs-parent:write

### volunteer_admin
organisations_details-parent:read
organisations_outreach-own:read
organisations_outreach-own:write
organisations_outreach-own:modify

user_details-own:read
user_details-own:write
user_details-own:modify

volunteer_activties-parent:read

volunteer_logs-parent:write

### cb_admin
organisations_details-own:read
organisations_details-own:write
organisations_details-own:modify
organisations_feedback-own:read
organisations_training-own:read
organisations_training-own:write
organisations_training-own:modify
organisations_invitations-own:read
organisations_invitations-own:write
organisations_invitations-own:modify
organisations_outreach-own:read
organisations_outreach-own:write
organisations_outreach-own:modify

user_details-own:read
user_details-own:write
user_details-own:modify
user-details-children:read
user-details-children:write
user-details-children:modify

volunteer_activities-own:read
volunteer_activities-own:write
volunteer_activities-own:modify
volunteer_logs-own:read

visit_activities-own:read
visit_activities-own:write
visit_activities-own:modify
visit_logs-own:read

### funding_body_admin
organisations_details-own:read
organisations_details-own:write
organisations_details-own:modify
organisations_details-children:read
organisations_details-children:write
organisations_details-children:modify

organisations_feedback-own:read
organisations_feedback-children:read

organisations_training-own:read
organisations_training-own:write
organisations_training-own:modify
organisations_training-children:read

organisations_invitations-own:read
organisations_invitations-own:write
organisations_invitations-own:modify
organisations_invitations-children:read

organisations_outreach-own:read
organisations_outreach-own:write
organisations_outreach-own:modify
organisations_outreach-children:read

user_details-own:read
user_details-own:write
user_details-own:modify
user-details-children:read //this needs to be anonymised!!!

volunteer_activities-children:read
volunteer_logs-activities:read

visit_activities-children:read
visit_logs-activities:read

### twine admin 
ALL THE ACCESS EVA

**Comment by astroash** [comment]
☝️ on second thought we may want CRUD operations, rather than using modify which combines update & delete, as some users may not have permission for both.

**Comment by eliascodes** [comment]
read/write/delete seems sufficient

**Comment by astroash** [comment]
Visitors are able to create visits, and feedback but are unable to update these. I'll see if this will be an issue whilst I'm mapping these permissions to routes.

**Comment by astroash** [comment]
Thoughts relating to permission in lastest api PR:

- In some cases -all, -chidlren & -own are interchangable if the definition of children is "details about myself or any entity that I own". If we adopt this definition -all could be removed. eg `/organisations`, `/organisations/:id`, `/:id/visit_activities`
- `POST: /organisations/:id` do we want users to be able to add a new organisation or will this only be done by twine or funding bodies?
- do we want cbAdmin to access their own data via a `/me` endpoint? eg they could access their visit data via `/organisations/:id/visit_activities` or `/organisations/me/visit_activities`. This will have an impact on permissions for routes. 
- `/organisations/:id/visit_activities` by allowing users to access their cbs deets with this endpoint we enable the permission `visit_activties-parent:read`. Depending on how we implement route logic, this will allow cbs who are owned by another cb/org (is this ever a case?) to view their parents cb/orgs visit activies. Potentially resolved by using a `/me` endpoint instead
- `/admin/me` returns admin user details with permission `user_details-own:read`. All users will have this permission so there may need to be additional checks to check role type.
- volunteers/visitors who are adding a log are currently writing to their `parent` org. Should this be considered as their `own` data as they are a member of the organisation?

@eliascodes let me know if you have any preferences on the above.

**Comment by eliascodes** [comment]
> POST: /organisations/:id do we want users to be able to add a new organisation or will this only be done by twine or funding bodies?

New organisations will be added by both the above, but also by CBs signing themselves up. See TwinePlatform/hq#10 for the sign-up scenarios.

> do we want cbAdmin to access their own data via a /me endpoint? eg they could access their visit data via /organisations/:id/visit_activities or /organisations/me/visit_activities. This will have an impact on permissions for routes.

I was thinking `/organisations/me/...`. What implications will this have?

**Comment by astroash** [comment]
My definition of `-parent ` is:

- cb's accessing information about their funding body
- visitors/volunteers accessing accessing information about their cb

Both of these are a accessing a direct parent so on second thought `/organisations/:id/visit_activities` is fine as it is. 

> >volunteers/visitors who are adding a log are currently writing to their parent org. Should this be considered as their own data as they are a member of the organisation?
>
>This speaks to a need to more closely define the notion of "parent". I don't know what the wider implications of this to your work are yet.

I think this is more of an issue of who is the owner of the resource, rather than the definition of "parent". Are "logs" owned by the visitor/volunteer who creates them, or are the "logs" owned by the cb with rights granted to visitors/volunteers.
