### ISSUE TITLE
changes to volunteer-logs routes

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#201]
**Changes**:
- ~~`GET /community-businesses/me/volunteer-logs/:id`~~
   - ~~if accessed by `VOLUNTEER`, should check that volunteer-log is owned by VOLUNTEER~~
- ~~`PUT /community-businesses/me/volunteer-logs/:id`~~
    - ~~should have `volunteer_logs-own:write` scope to allow `VOLUNTEER`s to edit their own logs~~
   - ~~if accessed by `VOLUNTEER`, should check that volunteer-log is owned by VOLUNTEER~~
- ~~`DELETE /community-businesses/me/volunteer-logs/:id`~~
    - ~~should have `volunteer_logs-own:delete` scope to allow `VOLUNTEER`s to delete their own logs~~
   - ~~if accessed by `VOLUNTEER`, should check that volunteer-log is owned by VOLUNTEER~~
- `POST /community-businesses/me/volunteer-logs/:id`
    - payload.id should be required and default to 'me' for `VOLUNTEER`s
    - change conditional to `if(payload.id !== 'me')`

EDIT:  VOLUNTEERs to use users/me/v-logs routes 
**Questions**:
- do `VOLUNTEER`s need access to `GET /community-businesses/me/volunteer-logs`? This returns individual users ids. If needed, this data should be stripped for `VOLUNTEER`s

**Comment by eliascodes** [comment]
> POST /community-businesses/me/volunteer-logs/:id

Should be `POST /community-businesses/me/volunteer-logs`

**Comment by eliascodes** [comment]
Fixed by #200
