### ISSUE TITLE
🚐 rename ORG_ADMIN -> CB_ADMIN

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#202]
The concept of ORG_ADMIN has changed since the initial designs of the api. ORGanisations can be either a funding body or community business. The user ORG_ADMIN has been designed to be an administrator for a community business. 

We should rename ORG_ADMIN -> CB_ADMIN throughout the codebase.

**Comment by eliascodes** [comment]
Fixed by #203
