### ISSUE TITLE
login enforces restricted privilage for TWINE_ADMIN

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#206]
https://github.com/TwinePlatform/twine-api/blob/41dc3947a58483633d4424614369328b16ba403e/src/api/v1/users/login.ts#L13-L23

All TWINE_ADMIN permissions are `full`, but they are forced to to `restricted` due to the current check on origin.

@eliascodes did you have a plan for how this would work? If not I can look into options.

**Comment by eliascodes** [comment]
Am I reading this wrong? It looks like the privilege level is set to 'full' unless the origin is `visitor.twine-together.com` or `localhost:3000`, which it shouldn't be when running the temp dashboard app?

I don't understand what the problem is, could you explain again please?

**Comment by astroash** [comment]
temp dashboard app is created by CRA so also uses `localhost:3000`

**Comment by eliascodes** [comment]
Oh. Can't we change that?

**Comment by astroash** [comment]
Are you suggesting this as a temporary fix or will we want to keep this long term?

**Comment by eliascodes** [comment]
I don't think it's a bad idea to have all our client apps running on different ports 🤷🏼‍♂️

**Comment by astroash** [comment]
>I don't think it's a bad idea to have all our client apps running on different ports 🤷🏼‍♂️

I agree. I'm not questioning changing local ports (it would obviously be beneficial to do this). I'm just curious if matching on origin is our long term plan here. It feels a little _app specific_ to design our api around this.

**Comment by eliascodes** [comment]
I haven't thought about this since it was implemented, but given our API is internal and we'll have only a handful of domains, this doesn't seem particularly onerous.

We've been given app-specific requirements with respect to authentication, they need to go somewhere.
