### ISSUE TITLE
🐛 password reset route not sending response

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#211]
https://github.com/TwinePlatform/twine-api/blob/ac9182404f3cffcf38ad3f30414cd8541fd92a45/src/api/v1/users/password.ts#L102-L107

**Problem:**
Password reset payload contains `token`, `password`, `passwordConfirm` to reset a users password. To ensure that the token is valid all unused tokens are grabbed from the db in hash form and compared to the token using bcrypt.

🚨 if a non valid token is sent an error is thrown but the response is never sent to the client 🚨
- logger claims a 200 status code was returned
- client receives no response
- response from L106 does not reach either of the hapi lifecycle hooks

**Attempted Solutions:**
(general)
- delete `./build`
- restart server/computer/electrical circuit

(in called method)
- console log the hell out of the model method. It is throwing an error!
- wrap `findAsync` in a try/catch

(in handler)
- internally wrap handler in a try/catch
- return null/{} instead of boom error
- return alternative boom error

**Comment by astroash** [comment]
# UPDATE

All is well, turns out the req was taking too long, and was time restricted by the client.

We should link reset codes to emails to avoid cycling through all valid token to speed up handler.

**Comment by eliascodes** [comment]
Fixed by #212
