### ISSUE TITLE
volunteer "projects"

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-api#213]
Related to TwinePlatform/twine-app#32

Feature request for "volunteer projects", which are user definable "tags" that sit in a hierarchy underneath "volunteer activities". In this way they are analogous to "visit activities" which sit under "visit activity categories".

It may be worth thinking through whether we do just want to have a hierarchical tags system, since this can then capture many features, and can save us from adding loads of tables for every new thing.

**Comment by eliascodes** [comment]
[This guide on hierarchical data in SQL](http://mikehillyer.com/articles/managing-hierarchical-data-in-mysql/) suggests two models. The adjacency model is simpler though less flexible and can become problematic when nesting becomes deep. However, IMO, for our purposes, it's likely to be sufficient.

```sql
CREATE TABLE tag (
  tag_id SERIAL UNIQUE NOT NULL,
  organisation_id INT NOT NULL,
  parent_id INT,
  name VARCHAR NOT NULL,

  CONSTRAINT ___ UNIQUE (tag_id, organisation_id, name)
);
```

**Comment by eliascodes** [comment]
The alternative is adding a new table to support the "projects" feature, with the same structure as the `vist`/`visit_activity`/`visit_activity_category` tables.

**Comment by eliascodes** [comment]
```sql
SELECT * FROM tags WHERE type='VOLUNTEER_CATEGORY'
```

```sql
SELECT * FROM tags WHERE type='VOLUNTEER_ACTIVITY' AND organisation_id=2
```

```sql
INSERT INTO tags (organisation_id, parent_id, name, type) 
VALUES (
  $1,
  (SELECT tag_id FROM tags WHERE type='VOLUNTEER_CATEGORY' name=$2),
  $3,
  'VOLUNTEER_ACTIVITY'
)
```

Problem then becomes how to store (potentially arbitrary) metadata related to a tag. As a concrete example: each visit activity is associated to days. The only practical option I can think of is to add a jsonb column and dump it in there, and clean it up in the model layer.

**Comment by astroash** [comment]
I don't think that _"projects"_ need to be nested under `volunteer_activity`. For instance a _"Community Dinner"_ project could be related to "Helping with raising funds (shop, events…)" and _"Professional pro bono work (Legal, IT, Research)"_ `volunteer_activity`s.

To offer flexibility we could add "projects" to a tags table, so that other tag types can be added at a later date

eg.

```
| tag_id | organisation_id |        name      |        type        |
|--------|-----------------|------------------|--------------------|
| 1      | 1               | Community Picnic | VOLUNTEER_PROJECT  |
| 2      | 1               | Holla back       | VOLUNTEER_PROJECT  |
```

**Comment by eliascodes** [comment]
Yeah, I think you're right about there not necessarily being a hierarchy in the concept of a volunteer "project".

On the tags thing, if we're now only implementing it for one thing, it doesn't seem worth it. I do like it as a general solution though. If and when another feature/concept fits into the "tags" thing, we can implement it then and port the data fairly simply.

I think I'll just go with something like a `volunteer_project` table.
