### ISSUE TITLE
🐛 visitor qr codes not being hashed - make it so everywhere

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#227]
🙈

**Comment by eliascodes** [comment]
They're not hashed at the moment because they need to be recoverable by the CB admin. Alternative that allows for hashing is that instead of being recoverable, they can be reset by the CB admin.

**Comment by astroash** [comment]
By recoverable, do you mean send another email with qr code?

**Comment by astroash** [comment]
Note, we're currently using bcrypt compare to find visitors based on their qr code.

**Comment by eliascodes** [comment]
lol, oh there's an inconsistency. QR codes in our test data are hashed, so the tests pass 🤭

OK, options:
1. Remove hashing:
   * Go through app logic and remove hash/compare from qr codes
2. Change visitor app:
   * remove the `<img>` tag displaying the QR code on the `Visitor.js` page
   * change "resend QR code" to "reset QR code" or similar
   * change "print QR code" to "print new QR code" or similar
   * add endpoint to generate new QR code for visitor

**Comment by astroash** [comment]
For me the decision comes down to weighing up these two benefits:

1. removing hashing will allow us to search the db for users by qr code, making the route more performant. async searching will get timely as cbs user base grows. 

2. adding hashed qr codes gives added security as they cannot be snooped on/stolen. 

I feel like point 2 is of lower importance as qr codes do not have any personal information attached to them, and currently are only used in conjunction with a CB_ADMIN auth cookie.

Can you think of any other tradeoffs with picking option one?

**Comment by eliascodes** [comment]
I can't think of any at the moment. The data-sync also doesn't hash the QR codes at the moment, just FYI. I suppose it's easer to go from non-hashed to hashed in the future if we need to, than the other way around.
