### ISSUE TITLE
CORS & Cookie problems

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-api#234]
### Problem
The `Set-Cookie` header doesn't appear to be part of the response in the browser when the client app is hosted on a different domain from the API. This is likely to be a configuration issue, but is at the moment mysterious 👻

### Things to try
* [x] Run client on `localhost:xxxx`, run API on `localhost:yyyy` (**WORKS**)
* [x] Run client on `192.168.a.b:xxxx`, run API on `localhost:yyyy` (**BORKS**)
* [x] Run client on `192.168.a.b:xxxx`, run API on `192.168.c.d:yyyy` (**WORKS**) @astroash 
* [ ] Try setting cookie domain explicitly
* [ ] Sniff packets sent from hapi server to determine whether `Set-Cookie` header is actually set by hapi and ignored by browser, or never set in the first place
* [x] Create a minimal reproducible example of the problem with hapi
* [x] Create a minimal reproducible example of the problem with express 🚫**BROKE**🚫 @astroash 
* [ ] Create a minimal reproducible example of the problem with vanilla node

**Comment by astroash** [comment]
Basic express server not giving cors errors but not setting cookie cross domains:

```js
var express = require('express')
var cors = require('cors')
var app = express()

var corsOptions = {
  origin: 'http://twinedev.com:3000',
  credentials: true
}

app.use(cors(corsOptions))

app.get('/', function (req, res, next) {
  res.send('TEST express server')
})

app.options('/v1/users/login', cors(corsOptions))

app.post('/v1/users/login', function (req, res, next) {
  res.cookie('twine', true)
  res.send('TEST express server')
})

app.listen(4001, function () {
  console.log('CORS-enabled web server listening on port 4001')
})
```

**Comment by astroash** [comment]
**Issue appears solved:**
- cookies sent when both client and server are on subdomains of the same domain
- volunteer app makes requests expecting a token response

**Tested on:**
admin.twine-together.com (client) & api.twine-together.com (server)
TF volunteer app 1.5.0 (8) (client) &  api.twine-together.com (server)

**Server changes when tested**:
- running of gh staging corsy branch
- rebuild db from staging in dev env
- cors origin "*"

**Next steps:**
- test with cors origin set to production domains
- rebuild android app as not currently working
- run datasync on production db **and readd frontline api key!!!**
