### ISSUE TITLE
Miscellaneous data model updates

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-api#24]
* [x] remove organisation_type from organisation since we may want to support multiple
* [x] make gender into table
* [x] sort out permissions in the model (is enum still appropriate, or should it be a table?)
* [x] Address inconsistencies identified in TwinePlatform/data-sync#8

**Comment by astroash** [comment]
re permissions

IMO we should keep this as an enum. Once we've settled on what our permission flags are, we should stick to them. Otherwise we'll have a whole load of rewriting on our hands.

**Comment by eliascodes** [comment]
> IMO we should keep this as an enum.

Fine with me, but all the enums are currently wrong because I was just guessing :)

> for organisation_type do we want to:
> * replace with an enum linking table 🚫
> * replace with an `organisation_type table and linking 🚫
> * remove completely for now ✅

**Comment by astroash** [comment]
@eliascodes side note,

some of the `seeds` are running `.truncate()` before inserting data, and some aren't. I can't seem to stop a pattern between environments and entities. Is there meant to be a pattern here or is it a typo?

For example, `community_business_region` truncated in testing and production but not development

**Comment by eliascodes** [comment]
Apologies, assume that the seeds in `development` are the canonical version for now. If the others don't match, they should be changed.

The reason I removed the `truncate` command is because Postgres complained about removing rows that were referenced by other tables.
