### ISSUE TITLE
Add support for multiple roles per user

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-api#247]
Many users have used the same e-mail to register as CB admins/volunteers/visitors because the old apps were running off of different DBs and had much weaker constraints.

The new data model does not allow duplicate e-mails, so multiple roles per user must be supported (otherwise we lose data).

**Comment by eliascodes** [comment]
### API
* Credentials object needs changing, `roles` attribute becomes either an array or object of roles.
* `/users/me/roles` should be an array
* is_child_organisation
* is_child_user
* require_sibling_user
* Roles.oneFromUser
* Permissions possibly needs new convenience method
* Remove DB constraint on one role per user

### Volunteer app
* `/users/me/roles`

### Data sync
* Port multiple roles instead of overwriting.

**Comment by astroash** [comment]
@eliascodes it's unclear from above how this is going to be implemented, but happy for you to do this as you see fit.

**Comment by eliascodes** [comment]
It wasn't meant to be that detailed, just a summary of areas that need work.

**Comment by eliascodes** [comment]
@astroash have just noticed that the list above (and the work I've done so far) doesn't include supporting new registrations of second roles (e.g. an existing volunteer signing up as a visitor). It only supports users who already have multiple roles due to the data-sync.

Do we want to support new registrations now or defer it?

**Comment by astroash** [comment]
Defer for now.
