### ISSUE TITLE
herkou build errors

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#253]
fyi @eliascodes 

documenting steps completed, feel free to close after reading
- master branch is deployed to twine-api but does not support cors for temp dashboard
- deployed staging to heroku pipeline twine-api, however deployment failed due to removal of flatmap-stream from npm:
```bash
-----> Restoring cache

       - node_modules

       

-----> Building dependencies

       Installing node modules (package.json + package-lock)

       npm ERR! code E404

       npm ERR! 404 Not Found: flatmap-stream@0.1.1
```
- disabled node caching on heroku
- still broke

**Comment by eliascodes** [comment]
This is because flatmap-stream was unpublished yesterday after it was found to contain malicious code. See my comment in the FAC gitter.

**Comment by eliascodes** [comment]
It's a dependency of nodemon, so I guess we could remove that for the time being.
