### ISSUE TITLE
🚨 Setup error logging for server

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#256]
Moving into production, it would be useful to save detailed error logs.

**Comment by eliascodes** [comment]
For now we can just log errors in the pre-response hook. It would also be useful to log user ID with every request to help with diagnostics and monitoring.

**Comment by eliascodes** [comment]
So for every request, we want:
* Origin
* User ID, if possible
* Request payload
* Timestamp
* Endpoint hit
* Status code
* Response size (bytes)
* User Agent? (for browser stats)

Anything else?

**Comment by eliascodes** [comment]
Closing for now, specific problems with this can be raised separately.
