### ISSUE TITLE
🗺 multiple regions per organisation

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#261]
From user testing it has been highlighted that Power to Change is linked to the London region, but has offices in Sheffield and Bristol. Multi region organisations can be supported by having a linking table.

@edwardwptc do we know if there are any other organisations that are operating in multiple regions?

**Comment by edwardwptc** [comment]
Only funding organisations so far I think, like PTC. 

All the grantees and other users have a specific local area at this time, or at the very least a "home area". 

For Power to Change to fund an organisation it needs to meet criteria about being "locally rooted" so at least for the time being until we get more private customers, all grantees at the very least will be in one area.

**Comment by astroash** [comment]
Thank you @edwardwptc. We'll deprioritise this issue for now.

**Comment by astroash** [comment]
Irrelevant for p2c use cases
