### ISSUE TITLE
🔐 bcrypt is not able to compare old passwords

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#265]
PHP server uses bcrypt to store passwords. When comparing passwords in node, bcrypt returns false.

**Comment by eliascodes** [comment]
PHP uses non-standard notation to specify the algorithm, the solution to this is to replace the `$2y$` at the beginning of the hash with a `$2a$`.

This should be fixed in the data-sync.

**Comment by eliascodes** [comment]
This was fixed
