### ISSUE TITLE
🗃 Deleting foreign key rows

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#285]
A number of foreign keys constraints have `ON DELETE CASCADE`. This is not always the functionality that we want. In some instances we want to set this value to null.

**Comment by astroash** [comment]
@eliascodes, for the above to be implemented we will need to remove `NOT NULL` constraints on a number of rows. 

The places I was thinking of implementing:
- references to user_id. Most of this data is related/owned by a cb. A user should be able to be hard deleted without cbs loosing anonymised data.
- any _descriptive_ data such as `outreach_meeting_type`

I can stick a pr up with what I imagine this looking like to see if it's worth the change

**Comment by eliascodes** [comment]
I don't think we're currently planning on hard deleting any rows in the `user_account` table. When a user requests to be deleted, their personal information will be anonymised, but the record will still exist (and be tied to demographic data, for example).

Given that, I don't think it's beneficial to remove null constraints on user ID right now.
