### ISSUE TITLE
Create an abstraction module for email clients

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#29]
Create a module for sending emails that takes the following options
Optional properties are marked with `?`
```
{
  from: String,
  to: String,
  templateId: Number,
  templateInserts: {}
  attachements?: [{
    filename: String,
    path?: String,
    href?: String,
    contentType: String
  }]
}
```

`templateId` can either refer to an external template hosted by an email client or a local template

`templateInserts` will consist of key's relating to specific templateIds and values to be inserted.

**Comment by eliascodes** [comment]
I'm assuming from what you've written that this module will expose only one method, which will be used to send a single e-mail.

Is that all the functionality we're likely to need? What about the ability to send multiple e-mails at once? Anything else?

How will the e-mail client be managed? From within the module? How does it interact with the project configuration? For example, if I ran this code in a test environment, would it always talk to the real server and send a real e-mail?

**Comment by astroash** [comment]
> I'm assuming from what you've written that this module will expose only one method, which will be used to send a single e-mail.

I was thinking of something like this:
```
type Email = {
  from: String,
  to: String,
  templateId: Number,
  templateInserts: { <key>: String }
  attachements?: [{
    filename: String,
    path?: String,
    href?: String,
    contentType: String
  }]
}

type LocalTemplate = {
  subject: String,
  text: String,
  templateInserts: { <key>: String }
}

type RemoteTemplate = {
  client: String,
  remoteId: Number,
}

Email.send :: Email -> Promise()
Email.sendMany :: Email[] -> Promise()
Email.addTemplate LocalTemplate || RemoteTemplate -> Number
Email.viewTemplateAll :: { id: Number, template: LocalTemplate || RemoteTemplate }
Email.viewTemplate :: Number -> LocalTemplate || RemoteTemplate
```

> How will the e-mail client be managed? 

I'm struggling to think how this would work, whilst being an abstraction and making it easy to switch between different clients. Suggestions welcome.

**Comment by eliascodes** [comment]
In [twine-visitor](https://github.com/TwinePlatform/twine-visitor) I instantiated the client at the application level, using the configuration object, then passed it down to the relevant functions as an argument.

This is OK, but actually poorly encapsulates the e-mail functionality; I have to worry about e-mail clients _outside_ the code directly concerned with the e-mail functionality.

Better would be keeping the instantiation logic inside the module, but requiring the module to be instantiated with a configuration object

**Comment by astroash** [comment]
Also, LMK if there's a preferred file structure.

**Comment by eliascodes** [comment]
More or less, yeah

```ts
type Config = {
  apiKey: string
}
```

Is probably all that's necessary for now. Not sure what you thought client name would be useful for?

I'm imagining a workflow a little like this:
```ts
import EmailService from 'wherever';

const Email = EmailService.init(config);

Email.sendBatch([
  {...},
  {...},
])
```

Directory structure is in the architecture docs.
