### ISSUE TITLE
👱🏻‍♂️ Supporting anonymous user accounts

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#298]
Some organisations create anonymous users so that they can scan the QR codes when people attend events.

eg:
anon woman
anon man
anon child

Currently this feature is not supported as user accounts need to be associated with an email. As a short term fix emails could be entered as a string such as `anon_[number]_org_[orgId]`. This would mean that emails will not be able to be sent for these accounts but their QR codes will be accessible from the visitor admin dashboard.

TwinePlatform/twine-visitor#607
TwinePlatform/data-sync#39

**Comment by eliascodes** [comment]
@astroash a user with a `NULL` email should still work, no?

**Comment by astroash** [comment]
I assumed that email was constrained to `NOT NULL`. I'm tempted to leave this as is for now as the faux email is minor and marks users who are created as 'anonymous' which may be of use in future.

**Comment by astroash** [comment]
**STILL TO DO:**

If we would like to allow CBs to create their own anonymous user accounts we will need to:

- refactor `register/visitors` to use `Visitors.addWithRole` or `Visitors.addAnonymousWithRole` dependent on payload

**Comment by eliascodes** [comment]
Is this still priority-2?
