### ISSUE TITLE
🗃 check max connections for role on postgres server

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#303]
When writing to the live database the following message was displayed:

```bash
too many connections for role "[DB_ROLE]"
```

Can be avoided by using transactions, but the limit should not be so low. Approx 20 connections were made.

**Comment by eliascodes** [comment]
https://devcenter.heroku.com/articles/postgres-logs-errors#fatal-too-many-connections-for-role

We should change the production config to assign max 20 connections to the pool.

**Comment by astroash** [comment]
Let's also make another user for us to connect to the db. 

I think I mentioned previously it would be really cool if we could have two dev db users:
- 1 read-only account that we use for checking issues
- 1 full-access account which we only use in cases of emergencies to fix errors on directly on the db

https://tableplus.io/blog/2018/04/postgresql-how-to-create-read-only-user.html

**Comment by eliascodes** [comment]
OK, I've created #309 about that. I think this can be closed once the max connection limit is lowered.
