### ISSUE TITLE
Create read-only roles for dev use

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-api#309]
From @astroash in #303:
> Let's also make another user for us to connect to the db.
>
> I think I mentioned previously it would be really cool if we could have two dev db users:
>
>  -  1 read-only account that we use for checking issues
>  -  1 full-access account which we only use in cases of emergencies to fix errors directly on the db
>
> tableplus.io/blog/2018/04/postgresql-how-to-create-read-only-user.html

Also useful:
https://devcenter.heroku.com/articles/heroku-postgresql-credentials#creating-a-new-credential

**Comment by astroash** [comment]
Cannot create additional credentials for `hobby` tier dbs
