### ISSUE TITLE
Improve password validation message

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-api#312]
Related to TwinePlatform/twine-app#73

**Comment by astroash** [comment]
@eliascodes this error message was handled in app by `twine-temp-dash`

https://github.com/TwinePlatform/twine-temp-dash/blob/80953c29af30321ae365a2fd6ffdba3ee980ad61/src/pages/PasswordReset.js#L61-L63

**Comment by eliascodes** [comment]
It works because I changed `endsWith` to `includes`.
