### ISSUE TITLE
Survey data and push endpoint for Frontline

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-api#32]
After our meeting yesterday, it was clear that the two tables in the [Twine-Admin](https://github.com/TwinePlatform/Twine-Admin) app that are storing survey data are storing aggregated data that would be useful for visualising cross-organisation statistics. This needs to stay in the data model.

This data was being pushed to the admin app DB by FrontlineSMS on a real-time basis, so we need to accommodate this by adding a push endpoint to the API spec and generating an API key for FrontlineSMS to use when pushing. See the original controller for this [here](https://github.com/TwinePlatform/Twine-Admin/blob/master/app/Http/Controllers/API/SurveyAnswerController.php)

**Comment by eliascodes** [comment]
Via e-mail from Frontline:

> **Twine survey median answer data**
> Every time an answer arrives through SMS into any Community Business workspace we, in addition to the usual survey processing, push the answer text to http://dashboard.twine-together.com/api/v1/survey-answers using a single (shared across all workspace) Reason-provided API Key.  The JSON looks like this:
> ```
> {
>    "apiKey": "${userData['api-key']}",
>        "payload": {
>            "answer_content": "<SMS TEXT>",
>            "answerUUID": “<ANSWER-UUID>",
>            "360GivingId": "${globalUserData['360GivingId']}"
>        }
> }
> ```
> I believe that Reason used to simply receive these and store them in the db; we were not yet set up to use this data.  So I think the first task is to simply connect up this pipe again so that the data is being saved.
>
> The next step will then be for the PHP server to have an API endpoint set up that can provide median statistics for each of the answers on request, or by pushing the data out regularly (TBC).  What is needed here is for the API to receive API Key (for auth) + UUID (which question) + 360GivingID (provides data such as the CB’s region which might be needed) and have a set of statistics calculated from the database data and returned; this may just be average or more (TBC).
>
> Here at Frontline we will then connect this up and present the median data on the same axes as the CB’s live survey answer data.
>
> **Central CLS data store**
> This will work in the same way as proposed above with the PHP server -> FrontlineSMS API bridge.  The data here is static and updated once a year.  The data will probably simply be numeric and associated again with each question’s UUID.
>
> FrontlineSMS would again send the same Key + UUID + 360ID so that regional data can be pulled and present that on the charts.

**Comment by eliascodes** [comment]
After speaking with @SonjaTwine both these items seem to be of different priority.

I'm just going to re-state my understanding of all this and then offer some suggestions:
* It is desirable for both elements (**aggregated answer data** and **CLS data**) to be available to Frontline/users by September. Of the two, having the **CLS data** available is of higher priority.
* It is part of Bourne's responsibilities to fix the existing "push" endpoint which will once again allow Frontline to push data into the database used by the admin dashboard.
* Frontline needs to access **aggregated data** either through an additional ("pull") endpoint, or through a regular "push" to Frontline. This is the Twine team's responsibility.
* The **CLS data** endpoint is also the Twine team's responsibility.
* The **CLS data** can be entered manually, for the time being.

As mentioned by @astroash the **CLS data** endpoint is comparatively simple to implement, and can be added (only) to the new API rather than having to duplicate functionality between the new API and the PHP app. If desired, this can be started as soon as the structure of the **CLS data** is specified. 

Ensuring Frontline's access to the **aggregated data** is probably simpler using a "pull" endpoint rather than pushing data out to them on a regular basis. This "pull" endpoint would need to be added to the existing PHP app for now, to avoid the likelihood of data inconsistency. This cannot be done before the handover from Bourne is complete.

Once we have reached [stage 4 on the roadmap](https://github.com/TwinePlatform/hq/blob/master/roadmap.md#stage-4---admin-dashboard-integration), this pull endpoint can be switched over to the new API.

This is all unless the aggregated data feature can wait until stage 4, in which case we can avoid the duplication between the new API and the PHP app.

**Comment by SonjaTwine** [comment]
Thanks for this! All sounds good, just three points:
- I had not discussed with Borne to fix the existing "push" endpoint on their end. It may quite likely be easier for us to wait until the end of this week, when they will stop working on Twine, and then fix it on our end? Let me know if/why I instead should put that on their list.
- "structure of the CLS data" - I should be able to confirm that this week or next, there are several options I'm trying to map from a user/data understanding point of view.
- It sounds like it would be preferable to wait until stage 4 with the aggregated data feature, and I'm happy for us to do that.

**Comment by eliascodes** [comment]
Closing in light of recent communications
