### ISSUE TITLE
Casing updates on CITEXT fields don't work

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-api#333]
Discovered in TwinePlatform/twine-temp-dash#12

Reproducing my comment here:
> I think this is because we're using the `CITEXT` data type. It looks like postgres is comparing the value we're trying to set to the value that's already there, and if they match, it doesn't actually do the update.
>
> So if we were using a `TEXT` data type, it would compare, for example, `Twine` to `twine`, notice a difference, and then update the value. But using `CITEXT`, there's an implicit application of `LOWER()`, so it is actually comparing `LOWER('Twine')` to `LOWER('twine')`, which is the same.
>
> Perhaps unhelpfully, in both cases, the query returns `UPDATE 1`, telling the client that a row has been updated.
>
> I came to this conclusion by trying to update org names: 
>```sql
>UPDATE organisation SET organisation_name='Extra workspace 150' WHERE organisation_id=X;
>```
>This returns `UPDATE 1` but the name remains `Extra Workspace 150`. But if we change anything else, then the update "works":
>```sql
>UPDATE organisation SET organisation_name='Extra workspace 151' WHERE organisation_id=X;
>```
>Now the name is `Extra workspace 151`.

**Comment by eliascodes** [comment]
`user_account.email` and `user_account.post_code` should remain `CITEXT`, but the rest can be changed to `TEXT`.

**Comment by astroash** [comment]
Oh wait, who don’t we just flip this process and make a case sensitive `UNIQUE INDEX` for citext columns?

Works in my head...

**Comment by eliascodes** [comment]
>  make a case sensitive `UNIQUE INDEX` for citext columns

How?

**Comment by astroash** [comment]
Ignore my weird previous suggestion, tested and doesn't work..

But case sensitive comparisions can be done on `CITEXT` usting `CAST()`, will look at the best way to implement this with `knex`.

Which columns do we want this to be added to? All columns using `CITEXT`?

**Comment by astroash** [comment]
Nope doesn't work. According to postgres' docs on `citext`:

> If you'd like to match case-sensitively, you can cast the operator's arguments to text.

I can get select to match case sensitive using:

```sql
select * from organisation where CAST(organisation_name AS TEXT)  ~ 'aperture'
```

But this doesn't update:
```sql
update organisation set organisation_name = 'aperture science' where CAST(organisation_name AS TEXT) = 'Aperture science';
```
And this produces a syntax error:
```sql
update organisation set CAST(organisation_name AS TEXT) = 'aperture science' where organisation_id = 1;
```

If you can think of any other ways to layout the sql command lmk!

**Comment by eliascodes** [comment]
I think you can use `::` for casting too. 
```sql
select foo::TEXT from bar;
```
But I don't think this will help you on updates.

**Comment by astroash** [comment]
Update:

kind person on the internet pointed out this should work - https://rextester.com/UXBQ87764

Above example is running postgres 9.6.2 citext 1.3
We are running postgres 10.4 citext 1.4

Will look into whether versions are the issue

**Comment by eliascodes** [comment]
I just ran this example on the old visitor app DB (running `psql (10.4, server 10.6 (Ubuntu 10.6-1.pgdg16.04+1))`).

It worked fine.

I then started to incrementally add missing bits from our current schema to the example, and the tipping point was the **update trigger**. This is somehow causing this problem.

**Comment by astroash** [comment]
Oooh, I tried to remove all the constraints to see if that was the issue. Didn't think of the triggers...
