### ISSUE TITLE
⬆️ update depenedencies

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#347]
1 package has been flagged with high vulnerability. We should update dependencies for this project.

**Comment by eliascodes** [comment]
Which package is high? `npm audit` returns only moderate severity alerts, Github alerts on `lodash` is `low`

**Comment by astroash** [comment]
<img width="663" alt="screenshot 2019-02-20 at 16 08 45" src="https://user-images.githubusercontent.com/14337958/53101343-d54c7600-3529-11e9-86c5-95fa32438cdc.png">

**Comment by eliascodes** [comment]
Ah, I was running it on a branch
