### ISSUE TITLE
👣 tracking user activity

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#348]
We are currently tracking login events. However as we have cookies that last for one month this can be deceptive as 1 login event can last for this period. I wonder whether it is worth us tracking "days active", so we create a log every day a user is active on the platform. 

@eliascodes let me know what you think of the technicalities of this before I open the discussion to the rest of the team.

**Comment by eliascodes** [comment]
We could hook into the `onPreHandler` event to do this without polluting every route.

One row for every day the user is "active" is probably the least aggregated quantity we could record for now, though maybe worth thinking about whether "day" is definitely the minimum timeframe of interest (IMO it is, but...).

**Comment by astroash** [comment]
Sweet, sounds like that that's a simple way to implement. I'll add this to our baseline agenda later. I'd also be keen to display this info on my current temp-dashboard changes for https://github.com/TwinePlatform/hq/issues/60

**Comment by astroash** [comment]
confirmed by @Shanozd that this would be a useful data point to collect. Placing a high priority as this is a minimal change, and it would be good to start collecting asap
