### ISSUE TITLE
✂️🚀 staging heroku db woes

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#356]
There has been a lot of changes to the data model recently with the change in direction of the project. I think this is likely to continue. To avoid staging migration issues I think we should create/initialize a postgres db per review app.

From my understanding this does not come with any additional costs.

Thoughts?

**Comment by eliascodes** [comment]
Let's do it

**Comment by eliascodes** [comment]
@astroash please remember to tag PRs with issues they fix
