### ISSUE TITLE
Identify "temp" organisations directly

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-api#361]
Based on discussion from #349 

"temp" organisations should be identified directly. 

Options:
1. adding a boolean column to the `organisation` table (e.g. `is_temp`)
1. adding a boolean column to the `user_account` table (e.g. `is_temp`)
1. adding a `account_type` column to the `organisation` table (e.g. `FULL`, `TEMP`, etc.)
1. adding a `account_type` column to the `user_account` table (e.g. `FULL`, `TEMP`, etc.)
1. adding a `account_type` column to the `subscription` table (e.g. `FULL`, `TEMP`, etc.)

The latter option is related to discussion about the future of the `subscription` table (#362).

**Comment by astroash** [comment]
@eliascodes, do you have a preference for moving forward?

**Comment by eliascodes** [comment]
I think we should do both (1) and (2) for now.

**Comment by eliascodes** [comment]
Done for now, but watch this space for new comments.
