### ISSUE TITLE
Store who creates a volunteer log

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-api#368]
From slack:

>  we need to get an idea on whether volunteers are putting in data themselves or whether the volunteer admins are putting it in for them

@astroash suggested solution:

> We can add a `created_by` column to the volunteer logs table that records which `user_id` adds the log

@Shanozd The above solution can be implemented fairly quickly, however, it's worth thinking about the following:
- How should logs created previously to the implementation of this feature be interpreted? Should we back-fill the data assuming that the user for whom it is created is also the creator? Or should we leave them blank?
- Are we also interested in who is editing records? If so, this starts to become a much more significant feature, moving towards something like audit logs. This seems like a step too far given our current needs, but thought I'd ask anyway.

**Comment by Shanozd** [comment]
@eliascodes lets leave the previous logs blank. When it comes to who is editing the logs, we don't need that data right now. Depending on requirements that may come up at a future point but for our current purposes we can get by without it.

**Comment by eliascodes** [comment]
This is closed by #369 (@astroash remember to tag PRs 🙂)
