### ISSUE TITLE
🗜 move all typings to own folder

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#379]
Typings are hanging out in random places. It would be good to move them to their own folder either in root, or using the same convention as jest eg types folder in every directory.

This may end up being a part of https://github.com/TwinePlatform/hq/issues/63

Relates https://github.com/TwinePlatform/twine-api/pull/370#discussion_r268076804

**Comment by eliascodes** [comment]
Will be part of the work done after migrating to monorepo
