### ISSUE TITLE
Community businesses belongs to many funding programmes

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-api#38]
User feedback via @SonjaTwine:

> On the "organisation" table, the value for "Funding programme" needs to be able to be more than 1 (i.e. a community business can be a member of several funding programmes)

**Comment by eliascodes** [comment]
What does it mean for a community business to be a member of several funding programmes?

The model relationship as it exists so far is that community businesses and funding programmes are related only through subscriptions. That is, a community business is considered a member of a funding programme if and only if its subscription is funded via that funding programme.

This doesn't seem to be compatible with the one-to-many relationship you are describing, so something is obviously a bit off with our model.

Under what conditions might a community business be considered a member of a funding programme?

**Comment by SonjaTwine** [comment]
True, that's what I thought based on how PTC does it (other funders apparently don't).

Can we have the funding programme info made independent of the subscription? I.e.
- Funding organisation buys subscription for Community Business (subscription associated only with Owner = Funding organisation and Beneficiary = Community Business). Can choose Subscription Type (that table should be independent of Funding Programme?).
- Funding organisation groups its Community Businesses into Funding programmes (essentially, this is just a group membership for an organisation, visible as a filter on the graphs on the superadmin dashboard)

**Comment by eliascodes** [comment]
We can do that in principle. I just want to be clear about what the concept of a funding programme is.

A summary of my understanding:
* A subscription can be purchased by a funding body for a community business with or without associating a funding programme to the community business.
* A funding body can add multiple funding programmes to the platform.
* A funding body can associate a community business with one or more funding programmes, if and only if it owns the community businesses subscription.
* A community business cannot be a member of two funding programmes whose owners are different funding bodies.

If all of the above are true, then this feels more or less like a 'tagging' feature.

If the last two bullet points are false, then I'm afraid I don't understand how this all works.

**Comment by SonjaTwine** [comment]
Thanks Elias.
I'm afraid if we want to future-proof it, then we need to acknowledge that the last two points are false. I had not thought that through fully, apologies!

An example: Community Business A has a grant from Funding Organisation "Big Lottery Fund" (through Funding Programme "Integration") that funds its English language courses, and another grant at the same time from Funding Organisation "Nesta" (through Funding Programme "Digital skills") that funds its digital skills courses. The Community Business has to report to both Funding Organisations through Twine on how many people are visiting/volunteers working on the courses etc.
That happens a lot in real life, so we should definitely cater to that.
Your concept of "tagging" sounds like what we would need - could we do it like this?
 
   

>  A subscription can be purchased by a funding body for a community business with or without associating a funding programme to the community business.
>     A funding body can add multiple funding programmes to the platform.
>     A funding body can associate a community business with one or more funding programmes, - **freely if and only if it owns that subscription**

If a funding body wants to buy a subscription for a community business, but finds out that this community business already has a subscription (whether bought on its own or through another funder), the funding body can pay an additional small fee, and in return add that community business to a funding programme (or more than one) of theirs. That tagging will then allow them to see the data from that community business just like the data from one of their own subscriptions.
There is a semi-competitor of Twine who uses that model: https://about.makerble.com/pricing-1/

How does that sound?

**Comment by eliascodes** [comment]
Presumably, we don't want to allow _any_ funding body to be able to pay to access the data of _any_ community business. We could restrict this by requiring the community business to confirm (by clicking a link in an email) every time a "third party" funding body wishes to purchase access to their data.

**Comment by SonjaTwine** [comment]
That's true, sounds good!
Does that work with the data model you had/were building?

**Comment by eliascodes** [comment]
No, but we can change it. Better now than later. Thanks.

**Comment by astroash** [comment]
@eliascodes can this be closed?
