### ISSUE TITLE
Changes to online db schema

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#44]
List of changes to online schema because of discrepancies with migrations:
- organistions `360_giving_id` -> `_360_giving_id`
- user_account_access_role `user_id` -> `user_account_id`

Discrepancies not changed:
- organisation `organistion_type` exists on online schema but not migrations. @eliascodes is this correct?

**Comment by eliascodes** [comment]
`organisation_type` is a discriminator field that is useful if (1) we ever want to be able to say if an organisation is a CB or funding body without making a join and (2) we want to enforce the constraint that an organisation is _either_ a community business _or_ a funding body.

Not sure we necessarily want the latter, not sure we really need the former right now. IMO leave it out.
