### ISSUE TITLE
fix linter

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-api#51]
tslint doesn't appear to be doing anything (e.g. auto-insertion of semi-colons, auto-indentation)

**Comment by astroash** [comment]
Have you installed the vscode package? It’s working for me.

**Comment by eliascodes** [comment]
I have, perhaps it's misconfigured. It picks up some rules, but leaves this:

https://github.com/TwinePlatform/twine-api/blob/96df8954b8507d1bff79767537577b3fb9f0e7b2/src/server.ts#L11

Notice the double space before `async` and the space on the wrong side of the `:`

**Comment by eliascodes** [comment]
Done
