### ISSUE TITLE
hapi-pino doesn't have typings

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-api#53]
Might be worth switching to something like "good" instead.

**Comment by eliascodes** [comment]
OK well, "good" doesn't have typings either 🙄

**Comment by astroash** [comment]
Remember that great logging function I wrote...

**Comment by astroash** [comment]
Setting up routes without logging is painful! I've set `good` up as a plugin and not having any typing errors. Happy to change later if needed...

**Comment by eliascodes** [comment]
This is irrelevant since we're not using `pino` at the moment.
