### ISSUE TITLE
🐛 Nested objects not required in config

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#66]
Not sure if this is by design but...

Nested objects in config schema are not required eg:

https://github.com/TwinePlatform/twine-api/blob/a8dbbd7e9891565dd6f39145ad615ef747c9b6e3/config/config.schema.ts#L47-L49

**Comment by eliascodes** [comment]
It is by design. There's only one key now, but that won't necessarily always be the case.

**Comment by eliascodes** [comment]
Misunderstood the question. Yes, they should be `required`.
