### ISSUE TITLE
Rename server start function

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#68]
After reading numerous hapi tutorials, I've come to the conclusion that it is best practice for the function to start up the server to be named `liftOff()`

References:
- [hapi — How to Set a Default Authentication Strategy](https://futurestud.io/tutorials/hapi-how-to-set-a-default-authentication-strategy)

**Comment by eliascodes** [comment]
In two years of using Hapi I've never once seen `liftOff` used. Where are these numerous tutorials? You've linked only one.

**Comment by astroash** [comment]
I real lots of tutorials, I saw this, I decided it’s best practise. 

# 🚀

**Comment by finnhodgkin** [comment]
Legit.

**Comment by eliascodes** [comment]
No.
