### ISSUE TITLE
CLS benchmark ingestion

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-api#71]
#69 

Need to write a script that will stick the data into the DB. Data will be delivered via e-mail, possibly unstructured.

**Comment by eliascodes** [comment]
Transcribed the data from spreadsheet to static JSON file, which is read in during the seed.

**Comment by eliascodes** [comment]
@SonjaTwine could you confirm whether the "wellbeing" questions included on the spreadsheet you sent us come from survey 15 or survey 18? It's not clear to me.

**Comment by SonjaTwine** [comment]
Hi,
actually it's survey ID 23 on my list.
Will confirm with Frontline.

**Comment by SonjaTwine** [comment]
Hi, so yes it is survey ID 23, with the following question IDs:
![screen shot 2018-08-21 at 09 17 19](https://user-images.githubusercontent.com/35500509/44389538-0a4c2180-a523-11e8-8e60-7b82845d77d2.png)

Surveys 15 and 18 are variations of a slightly different survey ("wellbeing changes"), which we've made up, therefore has no benchmark.
Hope that helps?
