### ISSUE TITLE
CLS benchmark endpoint

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-api#72]
#69 

Need to expose the CLS benchmark data on the API, via an endpoint that accepts a pre-authenticated token (since Frontline will be the only ones using it).

**Comment by eliascodes** [comment]
Proposed request shape:
```
GET <HOST>/api/v1/survey/cls
Headers:
Authorization: Bearer <TOKEN>
```

Proposed response shape:
```
{
  "data": {
    [SURVEY_ID]: {
      [QUESTION_ID]: {
        [REGION]: <CLS_MEAN>,
        ...
      },
      ...
    },
    ...
  }
}
```

@astroash thoughts? If Frontline need to get subsets of this data (e.g. for a specific region) we could potentially support that via query params.

**Comment by astroash** [comment]
@eliascodes are `SURVEY_ID` and `QUESTION_ID` both numerical values? If so it may be more explicit if they are nested under a key that states their purpose.

**Comment by eliascodes** [comment]
How's this?
```
{
  "data": {
    "surveys": {
      [SURVEY_ID]: {
        "questions": {
          [QUESTION_ID]: {
            [REGION]: <CLS_MEAN>,
            ...
          },
          ...
        }
      },
      ...
    }
  }
}
```
Seems quite nested. Equivalent array version:
```
{
  "data": [
    {
      "surveyID": Number,
      "questions": [
        {
          "questionID": Number,
          [REGION]: <CLS_MEAN>,
          ...
        },
        ...
      ]
    },
    ...
  ]
}
```

**Comment by astroash** [comment]
The second is good. The shape of the data for NPS data #70, so we probably want to nest the data under data types: 
```
"data": {
  "nationalBenchmark": [...],
  "NPS": [...]
}
```

**Comment by eliascodes** [comment]
We went with this:

```
GET https://<TWINE_API_DOMAIN>/api/v1/organisations/{360GIVING}/questions/{QUESTIONUUID}/cls

Headers: 
Authorization: Bearer <API_TOKEN>
```

If the question UUID corresponds to the NPS survey, the response body will be:
```
{
  “survey_id": “<SURVEYUUID>”,
  “score”: {
    “detractors”: {
      “range”: [4, 6],
      “score”: <SCORE_AS_PROPORTION_(0-1)>
    },
    “passives”: {
      “range”: [7, 8],
      “score”: <SCORE_AS_PROPORTION_(0-1)>
    },
    “promoters” {
      “range”: [9, 10],
      “score”: <SCORE_AS_PROPORTION_(0-1)>
    }
  }
}
```
If the question UUID corresponds to any other question, the response body will be:
```
{
  “survey_id": “<SURVEYUUID>”,
  “region”: “<REGION_NAME>”,
  “mean_score”: <CLS_MEAN_SCORE>
}
```
