### ISSUE TITLE
Type checker

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-api#8]
Thoughts on using flow?

**Comment by astroash** [comment]
I'm pro static typing, although I will miss my HM type signatures.

**Comment by eliascodes** [comment]
Next step to spike implementation/workflow stuffs

**Comment by eliascodes** [comment]
Err, actually, maybe TS: https://github.com/niieani/typescript-vs-flowtype

**Comment by astroash** [comment]
I have a slight preference for flow as we can drop in and out of using it as we want, and it can [easily be removed](https://github.com/flowtype/flow-remove-types) if we decide to go for another system later down the line, ie I like it's non comital nature as I've not used either of them before.

https://codeburst.io/strict-types-typescript-flow-javascript-to-be-or-not-to-be-959d2d20c007

**Comment by eliascodes** [comment]
Your link is a 504
