### ISSUE TITLE
🔓 Middleware for scope authorisation

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#87]
### Permissions
The permissions have been designed to grant access dependent on the relationship between two entities. 

These relationships are described as:
- **parent** - allowing access to an entity that is owned by another entity
- **child** - allowing access to a entity that is owned by itself
- **own** - allowing access to an entities own information

### Hierarchy
```
| - twine
   |- funding body
      | - community business
         | - volunteer/visitor
```
**Data Ownership**
community business:
- visitor_logs
- volunteer_logs
- feedback
- outreach_campaign

user:
- user_details

### Scopes
Scopes follow the structure:
```
[entity] - [relationship] : [access]
organisations_details-child:read
```

Scope example:
Org admin have the scope `users_details-child:read`. This means that they can access details of any user that is in their organisation

Middleware needs to be created that:
- checks the role that is making the request and find out which entity they belong to
- check the relationship to the entity being accessed

**Comment by eliascodes** [comment]
This is mostly done. Some edge cases are not covered yet (#120), but this can be closed IMO.
