### ISSUE TITLE
Types for ramda

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#92]
Typing for TS on the following repo are meant to be significantly better than the ones on DefinitelyTyped

https://github.com/types/npm-ramda/

It's worth testing them out to see if it makes currying/composing easier in TS

**Comment by eliascodes** [comment]
If we can point to some concrete examples of things in this project that would be made easier by switching to these typings, then I'd be up for it. I am a little apprehensive though about the complexity of those types: Typescript build errors are already sometimes a little obtuse, I'm wondering whether it will be easy to tell that _something_ is wrong, but not exactly _what_.
