### ISSUE TITLE
Inconsistency in API spec

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-api#95]
https://github.com/TwinePlatform/twine-api/blob/a92ab82c47a5aaa8e8bfc551f0c43407202c7fd0/src/api/v1/api.json#L138-L146

Why does this (and other constant-routes) route have `auth: false`, but a defined `scope`? If the route is not authenticated, scope is irrelevant.

**Comment by astroash** [comment]
This is an oversight. `"auth": false,` was added after the scope value, and it was not removed.
