### ISSUE TITLE
👣 Cb sign up flow for visitor app

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#97]
@SonjaTwine currently community businesses can sign themselves up to the volunteer app by going to the following page: https://twine-visitor.herokuapp.com/cb/register

do we want to keep this functionality or is this to be removed so that you can control who signs up eg  by sending a sign up link to those who have subscribed to twine services?

<details>
<summary>technical details</summary>
To sign up a new cb the visitor app has a form that collects an organisations name, email, category, region and password. 

The old server/db allowed cbs to have their own account. The new db structure means that on sign up to the visitor app a new organisation , community business and org_admin user will be created. Below is the list of fields needed to create these, with the current data being collected in bold:

for organisation
- **organisation name**
- 360 giving id

for community business
- **region**
- **sector**
- street address
- town/city
- post code
- coordinates
- turnover band

for user
- name
- **password**
- gender
- disability
- ethnicity
- email
- number
- postcode
- year of birth
- contact consent

If we are to keep this sign up page either extra fields need to be added or a large number of empty fields will be created in the db.
</details>

**Comment by eliascodes** [comment]
@astroash That `<details>` thing is sick! Didn't know about it. Anyway, I figured we'd just leave most columns in the `user_account` table empty. We only want `password` and `email` really. Possibly `phone_number` will be useful for some yet-to-be-conceived feature far down the road.

**Comment by SonjaTwine** [comment]
@astroash thanks for raising this!
No, we definitely do not want to keep it entirely like it is for the longer term - bit of a risk, really, in case someone figures out that even though we currently communicate with them as if the link was restricted to current subscribers, actually anyone can sign up.

Yes, having a link that we can send to people who have signed up with us somewhere "offline" (i.e. paid and signed the Twine terms and conditions) would be ideal.

Then of course we'll want that integrated with the process of authenticating users across all three apps?

And we also need to collect all of the information you have listed there as technical details at some stage. As mentioned, that's probably easiest through a button click that pulls all the info (apart from "password") from Hubspot into our database? 
Then we just need to fit that in with the OAuth mechanism with Frontline and figure out the process (i.e. how does a user set a password once their organisation's data is on your app database).

Let me know if that helps?

**Comment by astroash** [comment]
@SonjaTwine do you have a time frame for wanting the restricted link?

Currently the above url is accessible from the homepage under a "Create new account" link. If you are manually emailing people with a link to https://twine-visitor.herokuapp.com/cb/register, I can remove this as an intermediary step.

**Comment by SonjaTwine** [comment]
@astroash thanks, I think that intermediary step would not necessarily add any security, since the thing I would be concerned about is just community businesses forwarding the link I sent them (which is the /register).

That is not a major risk for now because our users aren't really the people to wildly try out things with technology and links (I wish). So no specific deadline, but of course it would be good to get it eliminated soon.
What stage of your roadmap would that be easiest in?

**Comment by astroash** [comment]
@SonjaTwine I'm working on the admin pages of visitor app at the moment, if this is something that you would like done before the end of the roadmap I can look at it now. I'm just looking into the best way to add this feature without adding any additional complications when we create the super admin dashboard 

For new organisations that sign up:
- how often does this happen? (roughly how many do you expect by October?)
- what apps will they be using (dashboard, visitor app, volunteer app)
- will they all have a 360 giving id?

**Comment by SonjaTwine** [comment]
In that case, would be great if you could look at it now.
Re your questions:
- By october, I would expect max 20. These will be re-assigned existing accounts on the php web app (you'll have noticed we have quite a number of "extra workspace" organisations on there, plus some of the ones with actual accounts that we'll have to cancel by then), which are connected to the Frontline workspace, but new on the visitor app.
- I expect about 3 who will be using only the volunteer app, all others should get a subscription to everything
- yes, nobody gets a Twine account without one (they're based on their company numbers)

**Comment by astroash** [comment]
@eliascodes my suggestion for now:
- before hitting this route a `community_business`, `organisation` and `user` entry will already exist. This will be created manually through a script until the super admin dashboard is created.
- a one use token will be appended to the url sent as a link from sonja
- on success of sign up cb's will be prompted to set password if this is the first use of the account _(unsure of the best way to represent this in the db)_

db changes to be made:
- update `volunteer_admin_one_time_use_code` to `sign_up_one_time_use_code`

**Comment by eliascodes** [comment]
> on success of sign up

If the `community_business`, `organisation` and `user` entries are all created beforehand, what is left to be done on sign up? Surely the "sign-up" should just be setting the password? We could just re-use the "reset your password" functionality for this, no?

> update `volunteer_admin_one_time_use_code` to `sign_up_one_time_use_code`

The former is needed to escalate a normal volunteer sign up to a volunteer admin sign up, we can't get rid of it, and it doesn't serve the same purpose as what you're describing for the CB admin (effectively an invitation code).

**Comment by astroash** [comment]
> If the community_business, organisation and user entries are all created beforehand, what is left to be done on sign up? Surely the "sign-up" should just be setting the password? We could just re-use the "reset your password" functionality for this, no?

Good point. I was thinking of a minimal creation of `community_business`, `organisation` and `user` which will still need additional fields, but I don't think that should be the responsibility of this app. If we're having an admin account that can be used across our apps, then this should be done elsewhere.  I'm leaning towards dropping this route/page altogether and having it as part of the super admin dashboard. 

> The former is needed to escalate a normal volunteer sign up to a volunteer admin sign up, we can't get rid of it, and it doesn't serve the same purpose as what you're describing for the CB admin (effectively an invitation code).

From my understanding the volunteer admin code is an invitation code handed out by Sonja to allow volunteers to sign up with admin accounts.

**Comment by SonjaTwine** [comment]
> From my understanding the volunteer admin code is an invitation code handed out by Sonja to allow volunteers to sign up with admin accounts.

Yes exactly. We give out that admin code in our training materials.

**Comment by eliascodes** [comment]
Can this be closed?
