### ISSUE TITLE
🐛 CB model does not include cb id & org id

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#99]
`community_business_id`'s & `organisation_id`'s are different, however both aren't included in the model for community businesses. 

`organisation_id` is needed to to link users to roles.

**Comment by astroash** [comment]
On second thought, I think it is simpler if we remove `community_business_id` altogether. `community_business` table does not need a serial key, as an entry will never exist without a corresponding `organisation_id`. This should be a one to one relationship. Any organisation that owns other cbs, should be separate with a corresponding `funding_body` entry*.

_*`funding_body_id` should also be removed_

**Comment by astroash** [comment]
@eliascodes are you agreeing to the removal of both `community_business_id` and `funding_body_id`?

**Comment by eliascodes** [comment]
Yeah
